--crea un procedimuento al que le pasaremos el dni_cliente y la matricula. El procedimiento
--debera controlar en las ventas de los coches(tabla vende) los siguientes supuestos:

--  A.SI NO EXISTE UN REGISTRO CON DNI_CLIENTE Y ESA MATRILULA SALTAR A LA ZONA DE EXCEPCIONES
-- MOSTART UN MENSAJE
-- "NO EXISTE LA VENTA INTRODUCIDA"
-- B.SI EXISTE LA VENTA INPRODUCIDA 
--      I. MOSTRAT EL PRECIO ANTIGUO
--      II. ACTUALIZAR EL PRECIO SUBIENDO 1000
--      III DEVOLUCION EN UN PARAMETRO DE SALIDA DEL PROCEDIMIENTO(PS_NUEVO_PRECIO) EL PRECIO 
-- NUEVO TRAS CREAR UN BLOQIE ANONIMO QUE LLAME EL PRECEDIMIENTO ANTERIOR Y MUESTRE EL PRECIO
-- DEVUELTO POR EL PRECEDIMIENTO

